[profile.default]
solc = '0.8.17'
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = []
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/tree/master/config